// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDToWupKWk9BIWIHreMdkDa5ZVLM6t99s4',
    appId: '1:429209040724:web:269cd9c137bd29f76efac1',
    messagingSenderId: '429209040724',
    projectId: 'flutter-authentication-1e2cf',
    authDomain: 'flutter-authentication-1e2cf.firebaseapp.com',
    storageBucket: 'flutter-authentication-1e2cf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkTOiHZSEUsz4zzSukwN7cO8G2U0R-CGY',
    appId: '1:429209040724:android:aab9d3d6cb52f6ee6efac1',
    messagingSenderId: '429209040724',
    projectId: 'flutter-authentication-1e2cf',
    storageBucket: 'flutter-authentication-1e2cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9jI5dlyINa4y6jFypHxJmDE8aJkHLcbE',
    appId: '1:429209040724:ios:f8bc187d487277fe6efac1',
    messagingSenderId: '429209040724',
    projectId: 'flutter-authentication-1e2cf',
    storageBucket: 'flutter-authentication-1e2cf.appspot.com',
    iosClientId: '429209040724-pkl858dgkm45qlrip042o2lcp7di8ioc.apps.googleusercontent.com',
    iosBundleId: 'com.example.blocDemoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9jI5dlyINa4y6jFypHxJmDE8aJkHLcbE',
    appId: '1:429209040724:ios:dddf7ba68e678fbe6efac1',
    messagingSenderId: '429209040724',
    projectId: 'flutter-authentication-1e2cf',
    storageBucket: 'flutter-authentication-1e2cf.appspot.com',
    iosClientId: '429209040724-0d4b8jlrf8fa829iouupg8g86tqhnn07.apps.googleusercontent.com',
    iosBundleId: 'com.example.blocDemoApp.RunnerTests',
  );
}
